jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run a one-line script
      run: echo Hello, world!
    - continue-on-error: true
      name: Run a multi-line script
      run: 'echo Add other actions to build,

        echo test, and deploy your project.

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
